playcodesync_demo/MainAdmin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Server.DoorServer.urls',namespace="DoorServer")),
]

playcodesync_demo/Server/DoorServer/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name="DoorServer"

urlpatterns = [
    path('',views.MainPage.as_view(),name='MainPage'),
    path("login/",views.LoginPage.as_view(),name='LoginPage'),
    path('logout/', LogoutView.as_view(next_page='DoorServer:LoginPage'), name='LogoutPage'),
    path('signupinit/',views.SignUpInitPage.as_view(),name='SignUpPageInit'),
    path("signupinit/<str:uuid>/",views.SignInPage.as_view(),name='SignInPage'),
    path('<str:username>/',include("Server.UserServer.urls",namespace="UserServer")),
]

#api키 관련 
urlpatterns += [
    path('signupinit/api/',include('Database.urls.DoorApiUrls',namespace="DoorApi"))
]

playcodesync_demo/Frontend/templates/base/CodeTutor_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- js -->
    <script type="module" defer src="{% static 'base/js/CodeTutor_base.js' %}"></script>
    {% block scripts %}{% endblock %}

    <!-- style -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{% static 'base/css/CodeTutor_base.css' %}" rel="stylesheet" type="text/css" />
    {% block css %}{% endblock %}

    {% block title %}{% endblock %}

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

playcodesync_demo/Frontend/templates/base/DoorServer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Play CodeSync index</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script defer type="module" src="{% static 'base/js/DoorServer_base.js' %}"></script>
    {% block script %}{% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Roboto+Mono:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?famil0y=Poppins:wght@400;50;600;700&amp;family=Volkhov:wght@700&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/DoorServer_base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block css %}{% endblock %}

    {% block title %}{% endblock %}
</head>
<body>
        {% block content %}{% endblock %}
        <!-- 아래 바닥을 만들어주면 좋을것같습니다. -->    
</body>
</html>

playcodesync_demo/Frontend/templates/base/UserServer_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script defer type="module" src="{% static 'base/js/UserServer_base.js' %}" ></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
    {% block scripts %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base/css/UserServer_base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Roboto+Mono:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?famil0y=Poppins:wght@400;50;600;700&amp;family=Volkhov:wght@700&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block css %}{% endblock %}

    {% block title %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light pt-3 pb-3">
        <div class="container">
            <a class="navbar-brand" href="{% url 'DoorServer:MainPage' %}"><img src="{% static 'base/img/CodeSyncLogo2.png' %}" height="40"
                    alt="logo" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon">
                </span>
            </button>
            <div class="d-flex ms-lg-4"> 
                {% if user.is_authenticated %} <!-- 사용자가 로그인한 경우에만 로그아웃 링크를 표시 -->
                <div id="userInfo-dash"><img src="{% static 'base/img/userfavicon.png' %}" height="50px"/>
                    <div id="userInfo-popup-dash">
                        <div class="userInfo-ni">
                            <div class="userFavicon"><img src="{% static 'base/img/userfavicon.png' %}" width="50px"/></div>
                            <div>
                                <div>{{ request.user.username }}</div>
                                <div style="font-size: 13px; color: rgb(128, 128, 128);">{{ request.user.email }}</div>
                            </div>
                        </div>
                        <div class="userInfo-btn">
                            <a href="{% url 'DoorServer:UserServer:UpdatePage' request.user.username %}"><button id="accountInfo-change-popup" class="accountInfo-change-popup">회원 정보 수정 ></button></a>
                            <a class="logOutbtn-popup" href="{% url 'DoorServer:LogoutPage' %}">Sign Out</a>
                        </div>
                    </div></div>
            
                {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <!-- 아래 바닥을 만들어주면 좋을것같습니다. -->
</body>
</html>