playcodesync_demo/MainAdmin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Server.DoorServer.urls',namespace="DoorServer")),
]

playcodesync_demo/Server/DoorServer/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name="DoorServer"

urlpatterns = [
    path('',views.MainPage.as_view(),name='MainPage'),
    path("login/",views.LoginPage.as_view(),name='LoginPage'),
    path('logout/', LogoutView.as_view(next_page='DoorServer:LoginPage'), name='LogoutPage'),
    path('signupinit/',views.SignUpInitPage.as_view(),name='SignUpPageInit'),
    path("signupinit/<str:uuid>/",views.SignInPage.as_view(),name='SignInPage'),
    path('<str:username>/',include("Server.UserServer.urls",namespace="UserServer")),
]

#api키 관련 
urlpatterns += [
    path('signupinit/api/',include('Database.urls.DoorApiUrls',namespace="DoorApi"))
]

playcodesync_demo/Server/DoorServer/forms.py
from Database import models
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError


class SignForms(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    class Meta:
        model = models.Galeo
        fields = ["username", 'email',"bnvs_code"]

    def clean_bnvs_code(self):
        bnvs_code = self.cleaned_data.get("bnvs_code")
        try:
            bnvs_code_box = models.Bnvs_Code.objects.get(code=bnvs_code)
            
        except models.Bnvs_Code.DoesNotExist:
            raise ValidationError("Invalid BNVS Code")
        return bnvs_code

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.bnvs_code = self.cleaned_data['bnvs_code']
        if commit:
            user.save()
        return user

playcodesync_demo/Server/DoorServer/views.py
from typing import Any
from django import http
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login 
from django.http import HttpResponse
from django.conf import settings
from Database import models
from django.core.cache import cache
from Database import models 
import json
from datetime import datetime
from . import forms

class MainPage (generic.FormView):
    template_name = "DoorServer/MainPage.html"
    form_class = AuthenticationForm
    success_url = "/"

    def form_valid(self, form):
        login(self.request,form.get_user())
        return super().form_valid(form)

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['username'] = self.request.user.username
        else:
            context["username"] = "default_username"
        return context

class LoginPage(generic.FormView):
    template_name = "DoorServer/LoginPage.html"
    form_class = AuthenticationForm
    success_url = "/"

    def form_valid(self, form):
        login(self.request,form.get_user())
        return super().form_valid(form)
    
class SignUpInitPage(generic.TemplateView):
    template_name = 'DoorServer/SignUpPageIntro.html'
    
    
class SignInPage(generic.FormView):
    template_name = "DoorServer/SignUpPage.html"
    form_class = forms.SignForms
    success_url = "/login/"

    def dispatch(self, request, *args: Any, **kwargs: Any):
        self.uuid = kwargs.get('uuid')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: Any):
        user = form.save()
        username = form.cleaned_data.get('username')
        cache_data = json.loads(cache.get(self.uuid))
        username = models.Galeo.objects.get(username=username)
        time_str = cache_data[3]  # '2023-11-05T03:02:59.981237' 형식의 문자열
        time_format = '%Y-%m-%dT%H:%M:%S.%f' if '.' in time_str else '%Y-%m-%dT%H:%M:%S'
        time_obj = datetime.strptime(time_str, time_format)
        
        accept_instance = models.UserAccept(
            username=username,
            token=self.uuid,
            accept1=cache_data[0],
            accept2=cache_data[1],
            subaccept=cache_data[2],
            time=time_obj,  # datetime 객체로 변환한 값 사용
        )
        accept_instance.save()
        return super().form_valid(form)
    
    

playcodesync_demo/Server/DoorServer/templates/DoorServer/LoginPage.html
{% extends 'base/DoorServer_base.html' %}
{% load static %}

{% block scripts %}
<script defer type="module" src="{% static 'DoorServer/js/LoginPage.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'DoorServer/css/LoginPage.css' %}">
{% endblock %}

{% block title %}
<title>로그인 페이지</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center"><a href="/"><img src = "{% static 'DoorServer/img/CodeSyncLogo2.png' %}" style="width: 250px;"></a> </div>
    <p class="text-center mt-5 ment">Sign In to Play CodeSync</p>
    <div class="form-cover">

        <form method="post">

        <!--유저 아이디 적는칸-->
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
            {% csrf_token %}
            <input type="text" class="form-control" id="username" name="username" required>
            {% if form.username.errors %}
                <div class="error">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <!--비밀번호 적는칸 이 알맹이만 살아 있으면 문제 없을것입니다. -->
        <div class="mb-3">
            <label for="{{ form.password.id_for_label }}" class="form-label">Password</label>
            {% csrf_token %}
            <input type="password" class="form-control" id="password" name="password" required>
            {% if form.password.errors %}
                <div class="error">{{ form.password.errors }}</div>
            {% endif %}
        </div>

        <input type="submit" value="Login" class="btn btn-primary" style="width: 100%;">

        </form>

    </div>
    <div class="etc">
        <a href="">Terms</a>
        /
        <a href="">Privacy</a>
        /
        <a href="">Contact BNVS</a>
    </div>
</div>


{% endblock %}

playcodesync_demo/Server/DoorServer/templates/DoorServer/MainPage.html
{% extends 'base/DoorServer_base.html' %}
{% load static %}

{% block script %}
<script defer type="module" src="{% static 'DoorServer/js/MainPage.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'DoorServer/css/MainPage.css' %}">
{% endblock %}

{% block title %}
<title>메인페이지</title>
{% endblock %}

{% block content %}
<main class="main" id="top" style="height: 100vh;">
    <nav class="navbar navbar-expand-lg navbar-light pt-3 pb-3">
        <div class="container">
            <a class="navbar-brand" href="/"><img src="{% static 'base/img/CodeSyncLogo2.png' %}" height="40" alt="logo" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon">
                </span>
            </button>

            <div class="d-flex ms-lg-4"> 
                {% if user.is_authenticated %}
                <div class="nav-hello fs-4">{{ request.user.username }}님 <i class="fas fa-hand-paper fa-lg fa-rotate-45 ms-1" style="color: #ffd753;"></i></div>
                <a class="btn btn-warning btn-signup btn-lg fw-bold ms-3" href="{% url 'DoorServer:LogoutPage' %}">Sign Out</a> 
                {% else %}
                <button class="btn btn-secondary-outline btn-lg fw-bold" id="loginButton">로그인</button>
                <a class="btn btn-warning btn-signup ms-3 btn-lg fw-bold" href="{% url 'DoorServer:SignUpPageInit' %}">Sign Up</a> 
                

                <!-- 로그인 모달 -->
                <div id="loginModal" class="modal">
                    <div class="modal-content">
                        <div class="close">&times;</div>
                        <!-- 로그인 폼 내용 -->
                        <div class="container pt-4">
                            <div class="d-flex justify-content-center"><a href=""><img src="{% static 'DoorServer/img/CodeSyncLogo2.png' %}"
                                        style="width: 250px;"></a> </div>
                            <p class="text-center mt-3 ment">Sign In to Play CodeSync</p>
                            <div class="form-cover mb-3">
                        
                                <form method="post">
                        
                                    <!--유저 아이디 적는칸-->
                                    <div class="mb-3">
                                        <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                                        {% csrf_token %}
                                        <input type="text" class="form-control" id="username" name="username" required>
                                        {% if form.username.errors %}
                                        <div class="error">{{ form.username.errors }}</div>
                                        {% endif %}
                                    </div>
                        
                                    <!--비밀번호 적는칸 이 알맹이만 살아 있으면 문제 없을것입니다. -->
                                    <div class="mb-3">
                                        <label for="{{ form.password.id_for_label }}" class="form-label">Password</label>
                                        {% csrf_token %}
                                        <input type="password" class="form-control" id="password" name="password" required>
                                        {% if form.password.errors %}
                                        <div class="error">{{ form.password.errors }}</div>
                                        {% endif %}
                                    </div>
                        
                                    <input type="submit" value="Login" class="btn btn-primary" style="width: 100%;">
                        
                                </form>
                        
                            </div>
                            <div class="etc">
                                <a href="/">Terms</a>
                                /
                                <a href="/">Privacy</a>
                                /
                                <a href="/">Contact BNVS</a>
                            </div>
                        </div>
                    </div>
                </div>               
                {% endif %}
            </div>
        </div>
    </nav>
    <section class="info-section">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 text-md-start text-center pt-custom py-6">
                    <!-- <div class="tname">Play CodeSync</div> -->
                    <h1 class="mb-3 fs-1">재미있고 쉬운 코딩, <br />지금 시작하세요!</h1>
                    <div class="mb-3 lead fs-5">
                        <div class="mb-2">
                            AI와 함께하는 코딩세상에 
                            뛰어들 준비가 되었나요?
                        </div>
                        <div class="mb-2">
                            재미있고 쉽게 당신에게 딱 맞는
                            코딩 학습을 시작해 봐요!
                        </div>
                        <div>
                            CodeSync와 함께라면,
                            프로그래밍이 놀이가 됩니다!
                        </div>
                    </div>
                    <div class="text-center text-md-start">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            과목선택 
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <a class="btn btn-warning me-3 btn-lg fw-bold" href="{% url 'DoorServer:UserServer:MainPage' username %}" role="button">파이썬일반</a>
                        </ul>
                        <button id="guideButton" class="btn btn-link text-warning fw-medium text-black"><span class="fas fa-play me-2"></span>User Guide</button>
                    </div>
                </div>
                <div class="col-md-6 text-end pt-custom"><img class="pt-7 pt-md-0 img-fluid index-img" src="{% static 'DoorServer/img/index_img.png' %}" width="550" alt="" /></div>
            </div>
        </div>
    </section>
    <!-- User Guide 모달 -->
    <div id="guideModal" class="guideModal">
        <div class="guideModal-content">
            <div class="guideclose">&times;</div>
        
            <img src="{% static 'DoorServer/img/userguide_horizon.png' %}" style="width: 90%; margin-top: 150px;">

            <!-- </div> -->
        </div>
    </div>
</main>
{% endblock %}

playcodesync_demo/Server/DoorServer/templates/DoorServer/SignUpPage.html
{% extends 'base/DoorServer_base.html' %}
{% load static %}

{% block scripts %}
<script defer type="module" src="{% static 'DoorServer/js/SignUpPage.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'DoorServer/css/SignUpPage.css' %}">
{% endblock %}

{% block title %}
<title>회원가입 페이지</title>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center"><a href="/"><img src = "{% static 'DoorServer/img/CodeSyncLogo2.png' %}" style="width: 250px;"></a> </div>
    <p class="text-center mt-5 ment">Sign Up to Play CodeSync</p>
    <div class="form-cover">
        <form method="post">
            <!--회원가입 아이디-->
            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                {% csrf_token %}
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error">{{ form.username.errors }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                <!--회원가입 비밀번호-->
                <label for="{{ form.password1.id_for_label }}" class="form-label">Password</label>
                {% csrf_token %}
                {{ form.password1 }}
                {% if form.password1.errors %}
                    <div class="error">{{ form.password1.errors }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                <!--회원가입 확인 비밀번호-->
                <label for="{{ form.password2.if_for_label }}" class="form-label">Confirm Password</label>
                {% csrf_token %}
                {{ form.password2 }}
                {% if form.password2.errors %}
                    <div class="error">{{ form.password2.errors }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                <!-- 회원가입 이메일 작성  -->
                <label for ="{{ form.email.id_for_label }}" class="form-label">E-mail</label> 
                {% csrf_token %}
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="error">{{ form.email.errors }}</div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="{{ form.bnvs_code.id_for_label }}" class="form-label">BNVs Token</label>
                {% csrf_token %}
                {{ form.bnvs_code }}
                {% if form.bnvs_code.errors %}
                    <div class="error">{{ form.bnvs_code.errors }}</div>
                {% endif %}
            </div>
            <input type="submit" value="회원가입" class="btn btn-primary" style="width:100%;">

        </form>
    </div>
</div>

{% endblock %}

playcodesync_demo/Server/DoorServer/templates/DoorServer/SignUpPageIntro.html
{% extends 'base/DoorServer_base.html' %}
{% load static %}

{% block title %}
<title>회원가입 약간</title>
{% endblock %}

{% block script %}
<script defer type="module" src="{% static 'DoorServer/js/SignUpPageIntro.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'DoorServer/css/SignUpPageIntro.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex justify-content-center"><a href="/"><img src = "{% static 'DoorServer/img/CodeSyncLogo2.png' %}" style="width: 250px;"></a> </div>
    <p class="text-center mt-5 ment">Agree to Terms to Create Your Account</p>
    <div class="mainContainer">

        <div class="form-cover">
            <div id="acceptContainerOne">
                <div class="accordion" id="accordionExample1">
                    <!--첫번째 동의서 내용-->
                    <div class="form-check">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                CodeSync 이용 약관
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ratione blanditiis, velit qui quas at aliquam cumque voluptatum sit corrupti quaerat numquam quisquam cupiditate dicta, porro pariatur reiciendis quam quae facilis laborum labore quasi sunt error doloribus saepe. Ab corporis, minus a, vel libero placeat ullam, saepe dolorem eius ipsum aspernatur amet maxime dolorum ea unde nihil obcaecati est voluptate repudiandae dolor neque quibusdam reprehenderit culpa autem? Sint qui repellendus officia velit quis consequatur? Veritatis sapiente consectetur reprehenderit cumque aut sed tempora repellat, accusantium nihil mollitia vel recusandae fugiat delectus voluptatum dolores placeat ratione similique alias dignissimos omnis ullam sit? Eos.
                                </div>
                        </div>
                    </div>
                    <!--동의 버튼-->
                    <div class="submitBox mb-4 mt-2 ps-4 number1">
                        <input class="form-check-input checkedBox1 essential agr1" type="checkbox" data-value="no" id="flexCheckDefault1">
                        <label id="checkLabel1" class="form-check-label" for="flexCheckDefault1">
                            <span class="check-nssr">[필수]&nbsp;&nbsp;</span>
                            <span>동의 합니다.</span>
                        </label>
                    </div>
                </div>
            </div>
        <div id="acceptContainerTwo">
            <div class="accordion" id="accordionExample2">
                <!--두번째 동의서 내용-->
                <div class="form-check">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            개인정보 수집 및 이용
                        </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam illum nemo at voluptatum exercitationem dicta dolorem, repellat esse aliquid! Impedit molestiae vero nulla non, assumenda nobis blanditiis ratione quod numquam inventore totam aut deserunt dolorum. Sapiente doloribus libero in totam error dolorum fugit sed deleniti cupiditate impedit quia, vel quidem sunt laboriosam iusto nulla earum velit saepe quas laborum aliquam. Quasi possimus, voluptatum nihil itaque fugiat unde? Repudiandae distinctio quo omnis sunt deserunt qui aliquid, labore, quia, a illo dignissimos? Ipsam distinctio explicabo error neque ducimus iste, non quis atque natus veniam molestiae necessitatibus temporibus in alias ullam blanditiis nam.
                        </div>
                        </div>
                    </div>
                <!--동의 버튼-->
                <div class="submitBox mb-4 mt-2 ps-4 number2">
                    <input class="form-check-input checkedBox2 essential agr2" type="checkbox" data-value="no" id="flexCheckDefault2">
                    <label id="checkLabel2" class="form-check-label" for="flexCheckDefault2">
                        <span class="check-nssr">[필수]&nbsp;&nbsp;</span>
                        <span>동의 합니다.</span>
                    </label>
                </div>
            </div>
        </div>
        <div id="acceptContainerTwo">
            <div class="accordion" id="accordionExample3">
                <!--세번째 동의서 내용-->
                <div class="form-check">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            개인정보 수집 및 이용
                        </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolor corporis deserunt culpa enim ex suscipit beatae sequi eveniet earum consectetur natus ipsam nostrum et cumque esse explicabo blanditiis accusantium, quas, porro architecto? Iure corporis, hic dolore vero, natus ut quod provident possimus, enim totam deserunt quia pariatur reiciendis praesentium officia eveniet cumque doloribus alias excepturi tempora molestiae! Culpa ducimus, non nesciunt accusantium voluptas explicabo nemo aspernatur dolores dolorum doloribus tempora pariatur amet nam impedit dicta, quos saepe dolor, id alias? Neque quos eveniet aut, ipsam odit reprehenderit! Ducimus temporibus quo unde beatae assumenda veniam repellat explicabo voluptatem hic cupiditate.
                        </div>
                        </div>
                    </div>
                <!--동의 버튼-->
                <div class="submitBox mb-4 mt-2 ps-4 number3">
                    <input class="form-check-input checkedBox3 choice agr3" type="checkbox" data-value="no" id="flexCheckDefault3">
                    <label id="checkLabel3" class="form-check-label" for="flexCheckDefault3">
                        <span class="check-otnl">[선택]&nbsp;&nbsp;</span>
                        <span>동의 합니다.</span>
                    </label>
                </div>
            </div>
            </div>
        </div>

        <button id="submitButton" class="btn btn-primary" style="width: 100%;">제출</button>
    </div>
</div>
{% endblock %}